[2023-12-20T19:08:11.742+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:08:11.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:08:11.745+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:08:11.745+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:08:11.767+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:08:11.764+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:08:11.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:08:11.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.061 seconds
[2023-12-20T19:08:42.079+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:08:42.080+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:08:42.081+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:08:42.081+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:08:42.098+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:08:42.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:08:42.099+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:08:42.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.067 seconds
[2023-12-20T19:09:12.385+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:09:12.387+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:09:12.390+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:09:12.389+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:09:12.421+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:09:12.416+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:09:12.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:09:12.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.098 seconds
[2023-12-20T19:09:42.713+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:09:42.714+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:09:42.715+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:09:42.715+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:09:42.726+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:09:42.725+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:09:42.727+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:09:42.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.048 seconds
[2023-12-20T19:10:55.223+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:10:55.226+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:10:55.228+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:10:55.227+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:10:55.251+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:10:55.249+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:10:55.252+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:10:55.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.064 seconds
[2023-12-20T19:11:25.569+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:11:25.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:11:25.571+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:11:25.571+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:11:25.589+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:11:25.586+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:11:25.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:11:25.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.073 seconds
[2023-12-20T19:11:55.920+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:11:55.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:11:55.922+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:11:55.922+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:11:55.942+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:11:55.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:11:55.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:11:55.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.055 seconds
[2023-12-20T19:12:26.284+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:12:26.285+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:12:26.287+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:12:26.286+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:12:26.302+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:12:26.300+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:12:26.302+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:12:26.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.047 seconds
[2023-12-20T19:12:56.665+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:12:56.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:12:56.666+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:12:56.666+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:12:56.679+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:12:56.678+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:12:56.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:12:56.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.044 seconds
[2023-12-20T19:13:27.061+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:13:27.062+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:13:27.064+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:13:27.063+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:13:27.082+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:13:27.080+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:13:27.082+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:13:27.115+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.062 seconds
[2023-12-20T19:15:35.033+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:15:35.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:15:35.038+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:15:35.038+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:15:35.061+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:15:35.059+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:15:35.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:15:35.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.080 seconds
[2023-12-20T19:16:05.459+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:16:05.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:16:05.467+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:16:05.465+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:16:05.502+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:16:05.500+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
ImportError: cannot import name 'fetch_and_process_delisted' from 'financial_etl' (/opt/airflow/dags/financial_etl/__init__.py)
[2023-12-20T19:16:05.504+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:16:05.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.094 seconds
[2023-12-20T19:16:35.769+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:16:35.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:16:35.774+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:16:35.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:16:35.802+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:16:35.801+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1
    from main import
                   ^
SyntaxError: invalid syntax
[2023-12-20T19:16:35.803+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:16:35.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.071 seconds
[2023-12-20T19:17:06.171+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:17:06.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:17:06.173+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:17:06.172+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:17:06.185+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:17:06.183+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1
    from main import
                   ^
SyntaxError: invalid syntax
[2023-12-20T19:17:06.185+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:17:06.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.045 seconds
[2023-12-20T19:17:36.543+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:17:36.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:17:36.546+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:17:36.545+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:17:36.562+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:17:36.560+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1
    from .main import
                    ^
SyntaxError: invalid syntax
[2023-12-20T19:17:36.562+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:17:36.593+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.055 seconds
[2023-12-20T19:18:06.984+0000] {processor.py:157} INFO - Started process (PID=203) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:18:06.986+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:18:06.987+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:18:06.986+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:18:07.011+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:18:07.009+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from db_utils import create_db_engine, insert_into_db
ModuleNotFoundError: No module named 'db_utils'
[2023-12-20T19:18:07.011+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:18:07.048+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.070 seconds
[2023-12-20T19:18:37.359+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:18:37.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:18:37.361+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:18:37.360+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:18:37.384+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:18:37.379+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from db_utils import create_db_engine, insert_into_db
ModuleNotFoundError: No module named 'db_utils'
[2023-12-20T19:18:37.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:18:37.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.062 seconds
[2023-12-20T19:19:07.771+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:19:07.772+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:19:07.773+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:19:07.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:19:07.792+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:19:07.789+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from db_utils import create_db_engine, insert_into_db
ModuleNotFoundError: No module named 'db_utils'
[2023-12-20T19:19:07.793+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:19:07.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.063 seconds
[2023-12-20T19:19:38.156+0000] {processor.py:157} INFO - Started process (PID=218) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:19:38.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:19:38.158+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:19:38.158+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:19:38.181+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:19:38.179+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 4, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:19:38.182+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:19:38.214+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.063 seconds
[2023-12-20T19:20:08.602+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:20:08.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:20:08.604+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:20:08.603+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:20:08.622+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:20:08.620+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 4, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:20:08.622+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:20:08.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.053 seconds
[2023-12-20T19:20:38.990+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:20:38.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:20:38.993+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:20:38.992+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:20:39.043+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:20:39.037+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 4, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:20:39.043+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:20:39.084+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.100 seconds
[2023-12-20T19:21:09.353+0000] {processor.py:157} INFO - Started process (PID=233) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:21:09.354+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:21:09.355+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:21:09.355+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:21:09.380+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:21:09.377+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:21:09.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:21:09.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.065 seconds
[2023-12-20T19:21:39.714+0000] {processor.py:157} INFO - Started process (PID=238) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:21:39.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:21:39.716+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:21:39.715+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:21:39.734+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:21:39.732+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:21:39.734+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:21:39.762+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.054 seconds
[2023-12-20T19:22:10.087+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:22:10.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:22:10.089+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:22:10.088+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:22:10.107+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:22:10.104+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:22:10.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:22:10.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.054 seconds
[2023-12-20T19:22:40.502+0000] {processor.py:157} INFO - Started process (PID=248) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:22:40.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:22:40.505+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:22:40.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:22:40.528+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:22:40.525+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:22:40.529+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:22:40.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.069 seconds
[2023-12-20T19:23:10.855+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:23:10.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:23:10.857+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:23:10.857+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:23:10.871+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:23:10.870+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:23:10.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:23:10.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.042 seconds
[2023-12-20T19:23:41.225+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:23:41.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:23:41.228+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:23:41.227+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:23:41.247+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:23:41.245+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:23:41.248+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:23:41.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.056 seconds
[2023-12-20T19:24:11.577+0000] {processor.py:157} INFO - Started process (PID=263) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:24:11.578+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:24:11.580+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:24:11.579+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:24:11.596+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:24:11.594+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:24:11.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:24:11.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.054 seconds
[2023-12-20T19:24:41.980+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:24:41.982+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:24:41.984+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:24:41.983+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:24:42.008+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:24:42.005+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:24:42.009+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:24:42.045+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.075 seconds
[2023-12-20T19:25:12.425+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:25:12.426+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:25:12.428+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:25:12.427+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:25:12.466+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:25:12.463+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:25:12.467+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:25:12.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.082 seconds
[2023-12-20T19:25:42.813+0000] {processor.py:157} INFO - Started process (PID=278) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:25:42.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:25:42.817+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:25:42.816+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:25:42.835+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:25:42.832+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:25:42.835+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:25:42.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.061 seconds
[2023-12-20T19:26:13.218+0000] {processor.py:157} INFO - Started process (PID=283) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:26:13.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:26:13.221+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:26:13.221+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:26:13.245+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:26:13.242+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:26:13.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:26:13.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.071 seconds
[2023-12-20T19:26:43.677+0000] {processor.py:157} INFO - Started process (PID=288) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:26:43.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:26:43.682+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:26:43.681+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:26:43.712+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:26:43.709+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:26:43.713+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:26:43.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.087 seconds
[2023-12-20T19:27:14.087+0000] {processor.py:157} INFO - Started process (PID=293) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:27:14.089+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:27:14.092+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:27:14.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:27:14.117+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:27:14.114+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:27:14.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:27:14.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.092 seconds
[2023-12-20T19:28:12.960+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:28:12.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:28:12.963+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:28:12.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:28:12.978+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:28:12.975+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:28:12.978+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:28:12.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.038 seconds
[2023-12-20T19:28:43.285+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:28:43.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:28:43.288+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:28:43.287+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:28:43.308+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:28:43.305+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:28:43.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:28:43.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.076 seconds
[2023-12-20T19:29:13.646+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:29:13.647+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:29:13.649+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:29:13.648+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:29:13.667+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:29:13.664+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:29:13.667+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:29:13.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.055 seconds
[2023-12-20T19:29:44.070+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:29:44.071+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:29:44.073+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:29:44.072+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:29:44.093+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:29:44.089+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:29:44.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:29:44.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.078 seconds
[2023-12-20T19:30:14.505+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:30:14.508+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:30:14.512+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:14.510+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:30:14.542+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:14.539+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from models import metadata
ModuleNotFoundError: No module named 'models'
[2023-12-20T19:30:14.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:30:14.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.080 seconds
[2023-12-20T19:30:44.894+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:30:44.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:30:44.897+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:44.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:30:46.716+0000] {processor.py:839} INFO - DAG(s) dict_keys(['financial_data_processing']) retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:30:46.865+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:46.865+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-20T19:30:46.873+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:46.873+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-20T19:30:46.882+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:46.882+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-20T19:30:46.883+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:46.883+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-20T19:30:46.907+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:46.906+0000] {dag.py:2963} INFO - Creating ORM DAG for financial_data_processing
[2023-12-20T19:30:46.916+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:30:46.915+0000] {dag.py:3722} INFO - Setting next_dagrun for financial_data_processing to 2023-01-01T00:00:00+00:00, run_after=2023-01-02T00:00:00+00:00
[2023-12-20T19:30:46.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 2.041 seconds
[2023-12-20T19:31:17.287+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:31:17.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:31:17.289+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:31:17.289+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:31:17.314+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:31:17.311+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from .models import metadatas
ImportError: cannot import name 'metadatas' from 'financial_etl.models' (/opt/airflow/dags/financial_etl/models.py)
[2023-12-20T19:31:17.314+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:31:17.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.064 seconds
[2023-12-20T19:31:47.707+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:31:47.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:31:47.712+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:31:47.711+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:31:47.734+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:31:47.732+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/finacial.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/finacial.py", line 4, in <module>
    from financial_etl import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/__init__.py", line 1, in <module>
    from .main import fetch_and_process_delisted, process_dividends_data
  File "/opt/airflow/dags/financial_etl/main.py", line 2, in <module>
    from .db_utils import create_db_engine, insert_into_db
  File "/opt/airflow/dags/financial_etl/db_utils.py", line 2, in <module>
    from .models import metadatas
ImportError: cannot import name 'metadatas' from 'financial_etl.models' (/opt/airflow/dags/financial_etl/models.py)
[2023-12-20T19:31:47.735+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:31:47.764+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.068 seconds
[2023-12-20T19:32:18.105+0000] {processor.py:157} INFO - Started process (PID=220) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:32:18.106+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:32:18.108+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:32:18.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:32:18.679+0000] {processor.py:839} INFO - DAG(s) dict_keys(['financial_data_processing']) retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:32:18.763+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:32:18.763+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-20T19:32:18.782+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:32:18.782+0000] {dag.py:3722} INFO - Setting next_dagrun for financial_data_processing to 2023-01-01T00:00:00+00:00, run_after=2023-01-02T00:00:00+00:00
[2023-12-20T19:32:18.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.696 seconds
[2023-12-20T19:32:48.939+0000] {processor.py:157} INFO - Started process (PID=338) to work on /opt/airflow/dags/finacial.py
[2023-12-20T19:32:48.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/finacial.py for tasks to queue
[2023-12-20T19:32:48.942+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:32:48.941+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/finacial.py
[2023-12-20T19:32:49.334+0000] {processor.py:839} INFO - DAG(s) dict_keys(['financial_data_processing']) retrieved from /opt/airflow/dags/finacial.py
[2023-12-20T19:32:49.353+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:32:49.353+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-20T19:32:49.370+0000] {logging_mixin.py:154} INFO - [2023-12-20T19:32:49.370+0000] {dag.py:3722} INFO - Setting next_dagrun for financial_data_processing to 2023-01-17T00:00:00+00:00, run_after=2023-01-18T00:00:00+00:00
[2023-12-20T19:32:49.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/finacial.py took 0.450 seconds
